name: Publish Go Binary

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 交叉构建,专为 ARMv7 架构编译
    strategy:
      matrix:
        include:
          - goarch: arm
            goos: linux
            goarm: 7  # 指定 ARMv7

    # 使用checkout
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with: 
        go-version: '>=1.16.0'
    - run: go version
    - name: make
      run: make
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
    - name: Packaging...
      run: tar czf nodeUpgrade-${{ matrix.goos }}-${{ matrix.goarch }}.tgz nodeUpgrade
    - name: Get version
      id: version
      run: echo "::set-output name=version::$(git rev-parse --short HEAD)"
    - name: Gets latest created release info
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag:  ${{ steps.version.outputs.version }}
          prerelease: true
          title: "Development Build"
          files: |
            ./nodeUpgrade-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goarm }}.tgz
